accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import login, logout
from . import views

app_name = 'accounts'

urlpatterns = [
	path('signup', views.signup, name='signup'),
	path('login/', login, name='login', kwargs={
			'template_name' : 'accounts/login_form.html',
		}),
	path('profile/', views.profile, name='profile'),
	path('logout/', logout, name='logout', kwargs={
			'next_page':reverse_lazy('root'),
		}),
]

baemin/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls',namespace='shop')),
    path('', lambda request: redirect('shop:index'), name='root'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,
						document_root=settings.MEDIA_ROOT)
	#미디어 url로 시작하는 요청이 오면 MEDIA_ROOT경로를 찾아서 파일을 보여줌

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path('', views.index, name='index'),
	path('category/<int:pk>/', views.category_detail, name='category_detail'),
	path('<int:pk>/', views.shop_detail, name='shop_detail'),
	path('<int:pk>/review/new/', views.review_new, name='review_new'),
	path('<int:shop_pk>/order/new/', views.order_new, name='order_new'),
	# path('<int:shop_pk>/order/<int:pk>/pay/', views.order_pay, name='order_pay'),
]

accounts/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.urls import reverse
from django.db import models
from jsonfield import JSONField

class Category(models.Model):
	name = models.CharField(max_length=100, db_index=True)
	icon = models.ImageField(blank=True)
	is_public = models.BooleanField(default=False, db_index=True)
	#공개된 카테고리만 찾고싶을때


	def get_absolute_url(self):
		return reverse('shop:category_detail', args=[self.pk])

	def __str__(self):
		return self.name

class Shop(models.Model):
	category = models.ForeignKey(Category, on_delete=models.PROTECT)
	name = models.CharField(max_length=100, db_index=True)
	desc = models.TextField(blank=True)
	latlng = models.CharField(max_length=100, blank=True)
	image = models.ImageField(blank=True)
	is_public = models.BooleanField(default=False, db_index=True)
	meta = JSONField() # NoSQL적 특성
	#공개된 가게

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:shop_detail', args=[self.pk])

	@property
	def address(self):
		return self.meta.get('address')
		#meta모델의 address를 가지고온다 없으면 none

class Review(models.Model):
	shop = models.ForeignKey(Shop, on_delete=models.PROTECT)
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
	photo = models.ImageField(blank=True)
	rating = models.SmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
	message = models.TextField()

	class Meta:
		ordering = ('-id',)
		#현재 id는 기본 primary키다		

	def __str__(self):
		return self.message

class Item(models.Model):
	shop = models.ForeignKey(Shop, on_delete=models.PROTECT)
	name = models.CharField(max_length=100, db_index=True)
	desc = models.TextField(blank=True)
	amount = models.PositiveIntegerField()
	photo = models.ImageField(blank=True)
	is_public = models.BooleanField(default=False, db_index=True)
	#공개된 아이템
	meta = JSONField()

	def __str__(self):
		return self.name

class Order(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
	amount = models.PositiveIntegerField()
	address = models.CharField(max_length=100)
	phone = models.CharField(max_length=11)

class OrderItem(models.Model):
	item = models.ForeignKey(Item, on_delete=models.PROTECT)
	quantity = models.PositiveIntegerField()
	order = models.ForeignKey(Order, on_delete=models.PROTECT)
	# amount

	@property
	def amount(self):
		return self.quantity * self.item.amount

shop/forms.py
from django import forms
from .models import Review, Order

class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review

		fields = ['rating', 'message', 'photo']

class OrderForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['address', 'phone']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy #success_url 활용 될때 순차적으로 실행하지않고 "게으르게" 실행
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

signup = CreateView.as_view(model=User, form_class=UserCreationForm,
							template_name='accounts/signup_form.html',
							success_url=reverse_lazy('root')) 
							#success_url이 활용이 될때 root실행



@login_required
def profile(request):
	return render(request, 'accounts/profile.html')

shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin #로그인 상황이 아니면 자동으로 이동시킴
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView
from .models import Category, Shop, Review, Order, OrderItem, Item
from .forms import ReviewForm, OrderForm



index = ListView.as_view(model=Category)

category_detail = DetailView.as_view(model=Category)

shop_detail = DetailView.as_view(model=Shop)

class ReviewCreateView(LoginRequiredMixin, CreateView):
	model = Review
	form_class = ReviewForm

	def form_valid(self, form):
		self.shop = get_object_or_404(Shop, pk=self.kwargs['pk'])
		#shop을 가지고와서 url의 pk값을 가지고온다
		#self.shop <- 멤버변수
		print(self.shop)
		review = form.save(commit=False)
		review.shop = self.shop
		review.author = self.request.user #현재 유저를 대응 author는 유저모델에 대한 외래키
		#django.contrib.auth.models.AnonymousUser
		#단순 파이선 클래스의 인스턴스
		return super().form_valid(form)

	def get_success_url(self):
		return self.shop.get_absolute_url()

review_new = ReviewCreateView.as_view()

@login_required
def order_new(request, shop_pk):
	item_qs = Item.objects.filter(shop__pk=shop_pk, id__in=request.GET.keys())
	#어떤 특정 shop에 있는 메뉴만 필터링 하겠다
	# item_dict = { item.pk: item for item in item_qs }
	#해당 쿼리셋을 순회하면서 사전을 만든다
	#어떤 메뉴 pk에 대한 어떤 메뉴

	quantity_dict = request.GET.dict()
	quantity_dict = { int(k): int(v) for k, v in quantity_dict.items() }
	#항상 모든 GET인자는 문자열 형태를 띄기떄문에
	#quantity_dict을 순회하면서 key와 value를 숫자로 변환해서
	#quantity_dict에 저장

	item_order_list = []
	for item in item_qs:
		#item 순회를 돌면서
		quantity = quantity_dict[item.pk]
		#quantity_dict에서 실제 주문수량을 뽑아내고
		order_item = OrderItem(quantity=quantity, item=item)
		#현재 어떤 item에 대해서 수량은 얼마나있는지 확인한다
		item_order_list.append(order_item)

	amount = sum(order_item.amount for order_item in item_order_list)
	#총 합계 계산
	instance = Order(amount=amount)

	if request.method == 'POST':
		form = OrderForm(request.POST, instance=instance)
		if form.is_valid():
			order = form.save(commit=False)
			order.user = request.user #유저가 같을때 저장
			order.save

			for order_item in item_order_list:
				order_item.order = order
			OrderItem.objects.bluk_create(item_order_list)
			#bluk_create 한번에 묶어서 쿼리처리

			return redirect('shop:order_pay', shop_pk, order.pk)
	else:
		form = OrderForm(instance=instance)

	return render(request, 'shop/order_form.html',{
		'item_order_list': item_order_list,
		'form':form,
		})

def order_pay(request):
	pass

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/login_form.html
{% extends "accounts/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h3>로그인</h3>

				<form action="" method="post">
					{% csrf_token %}
					<table class="table table-hover table-bordered">
						{{ form.as_table }}
					</table>
					<input type="submit" name="" class="btn btn-primary">
				</form>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h3>{{user}} 프로필</h3>
			
			<h4>주문내역</h4>

		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h3>회원가입</h3>
			<form action="" method="post">
				{% csrf_token %}
				<table class="table table-hover table-bordered">
					{{ form.as_table }}
				</table>
				<input type="submit" name="" class="btn btn-primary">
			</form>
		</div>
	</div>
</div>
{% endblock %}

baemin/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="/static/bootstrap-4.1.0/css/bootstrap.min.css">
  <link href="/static/fontawesome-free-5.0.10/web-fonts-with-css/css/fontawesome-all.css" rel="stylesheet">
	<script src="/static/jquery-3.3.1.min.js"></script>
  <script src="/static/underscore.js"></script>
	<script src="/static/bootstrap-4.1.0/js/bootstrap.min.js"></script>
	<title>요기요 테스트</title>
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">
      	<a href="{% url "root" %}">
      		요기요 st
      	</a>
  	  </h5>
      <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'accounts:profile' %}">프로필</a>
        <a class="p-2 text-dark" href="{% url "accounts:logout" %}">로그아웃</a>
      {% endif %}
      </nav>
      {% if not user.is_authenticated %}
        <a class="btn btn-outline-primary mr-1" href="{% url "accounts:login" %}">로그인</a>
        <a class="btn btn-outline-primary" href="{% url "accounts:signup" %}">회원가입</a>
      {% endif %}

    </div>
	{% block content %}
	{% endblock %}


	<hr />
	<div class="container">
		<div class="row">
			<div class="col-sm-12 mb-3">
			&copy; test 요기요
			</div>
		</div>
	</div>
  {% block extra-body %}
  {% endblock %}
</body>
</html>

shop/templates/shop/category_detail.html
{% extends 'shop/layout.html' %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h2>{{ category.name }}</h2>
			<div class="row">
					{% for shop in category.shop_set.all %}
						<div class="col-md-4">
			              <div class="card mb-4 box-shadow">
				              	{% if shop.image %}
					              	<a href="{{ shop.get_absolute_url }}">
					                	<img class="card-img-top" src="{{ shop.image.url }}" />
					                </a>
				                {% endif %}
                			<div class="card-body">
			                <p class="card-text">{{ shop.name }}</p>
			                <p class="card-text">
			                	{{ shop.desc }}
<!-- 			                	{{ shop.latlng }} -->
<!-- 			                	{{ shop.address }} -->
			                	{{ shop.is_public }}
			              	</p>
				                  <div class="d-flex justify-content-between align-items-center">
				                    <div class="btn-group">
				                    	<a href="{{ shop.get_absolute_url }}" class="btn btn-sm btn-outline-secondary">view</a>
				                    </div>
				                  </div>
			                  </div>
							</div>
						</div>
				{% endfor %}

			</div>
			<hr/>
			<a href="{% url "shop:index" %}" class="btn btn-primary">대문</a>
		</div>
	</div>
</div>

{% endblock %}

shop/templates/shop/category_list.html
{% extends 'shop/layout.html' %}


{% block content%}
<div class="container">
	<div class="row">

			{% for category in category_list %}


			<div class="col-md-4">
              <div class="card mb-4 box-shadow">
              	{% if category.icon %}
                	<img class="card-img-top" src="{{ category.icon.url }}" />
                {% endif %}
                <div class="card-body">
                  <p class="card-text">{{ category.name }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    	<a href="{{ category.get_absolute_url }}" class="btn btn-sm btn-outline-secondary">view</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
				{% endfor %}
	</div>
</div>

{% endblock %}

shop/templates/shop/layout.html
{% extends 'layout.html' %}

shop/templates/shop/order_form.html
{% extends "shop/layout.html" %}

{% block content %}
	{{form.instance.name}}
	{{form.instance.amount}}

	{% for item_order in item_order_list %}
		{{item_order.item.name}}
		{{item_order.quantity}}
		{{item_order.amount}}
	{% endfor %}

	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{form.as_table}}
		</table>
		<input type="submit" name="">
	</form>
{% endblock %}

shop/templates/shop/review_form.html
<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" />
</form>

shop/templates/shop/shop_detail.html
{% extends 'shop/layout.html' %}
{% load humanize %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12 mb-3">
			<h3>{{ shop.name }}</h3>
<!-- 
			{{ request.scheme }} 프로토콜 얻어옴
			{{ request.get_host }} 호스트를 얻어옴
			settings의 기본 context_processors 변수를 사용
-->
					
			<img src="https://openapi.naver.com/v1/map/staticmap.bin?clientId={{ settings.NAVER_MAP_CLIENT_ID }}&url={{ request.scheme }}://{{ request.get_host }}&crs=EPSG:4326&center={{ shop.meta.lng }},{{ shop.meta.lat }}&level=13&w=320&h=320&baselayer=default&markers={{ shop.meta.lng}},{{ shop.meta.lat }}">
			<table>
					<tr><th>주소</th><td>{{ shop.meta.address }}</td></tr>
					<tr>
						<th>전화번호</th>
						<td>
							<a href="tel:{{ shop.meta.phone }}">
								{{ shop.meta.phone }}
							</a>
						</td>
					</tr>
					<tr><th>최소주문 금액</th><td>{{ shop.meta.min_order_amount }}</td></tr>
					<tr><th>배달비</th><td>{{ shop.meta.delivery_fee_explanation }}</td></tr>
			</table>


			<hr/>
			<a href="{% url "shop:order_new" shop.pk %}"
			id="order-button" class="btn btn-primary btn-block mt-3 mb-3">주문하기</a>

			<table class="table table-bordered table-hover" id="item-list">
				<tbody>
				{% for item in shop.item_set.all %}
					<tr class="item" data-item-id="{{ item.id }}">
						<!-- 이 아이템에 대한 아이템 id가 {{무엇이다}}를 보여주게함 -->
						<td>
							{% if item.photo %}
							<a href="{{ item.get_absolute_url }}">
								<img src="{{ item.photo.url }}" style="width: 144px" />
							</a>
							{% endif %}
						</td>
						<td>{{ item.name }}</td>
						<td>{{ item.desc }}</td>
						<td>{{ item.amount|intcomma }}</td>
						<td>{{ item.is_public }}</td>
						<td>
							<i class='factor-button fa fa-minus-circle' data-factor='-1'></i>
								<span class="quantity">0</span>
							<i class='factor-button fa fa-plus-circle' data-factor='1'></i>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>

			<h3>리뷰</h3>
		<a href="{% url "shop:review_new" shop.pk %}" class="btn btn-primary">리뷰 쓰기</a>
		<table>
			<tbody>
			{% for review in shop.review_set.all %}
			<tr>
				<td>
					{{ review.message }}
					by {{ review.author }}
					{% if review.photo %}
						<img src="{{ review.photo.url }}" style="max-width: 200px;" />
					{% endif %}
				</td>
			</tr>
			{% endfor %}				
			</tbody>
		</table>

			<hr/>
			<a href="{{ shop.category.get_absolute_url }}">{{ shop.category.name }} 카테고리로</a>
			<a href="{% url "shop:index" %}">대문</a>
		</div>
	</div>
</div>
{% endblock %}

{% block extra-body %}
<script>
	$(function(){
		$('#item-list .item .factor-button').click(function(){
			// factor-button 클릭했을때 나오는 함수
			var $el = $(this).siblings('.quantity');
			// this는 factor-button를 가르침
			// sibling으로 quantity엘리먼트를 획득한다
			var factor = parseInt($(this).data('factor'));
			// 현재 factor-button에 data factor라는 항목을 가지고온다
			// 그 후 parseInt로 변환한다
			var quantity = parseInt($el.html()) + factor;
			// quantity에 있는 갯수가 실제 갯수
			// 그 갯수 값을 parseInt로 숫자로 변환 후 factor와 더함
			if ( quantity < 0 ) quantity = 0;
			// 현재 quantity가 0이하라면 강제로 0으로 만든다
			$el.html(quantity);
			// 증감된 값을 넣어준다
		});

	$('#order-button').click(function(){
	//클릭 리스너에서 href를 이동할때
	//참이냐 거짓이냐를 판단한 후 결정
		var mapped = _.map($('#item-list .item'), function(item){
			//각각의 tr태그를 순회한 후 인자function(item)로 넘겨준다
			var item_id = $(item).data('item-id');
			//각각의 상품별 jqurey인스턴스
			//item_id는 특정 item에 대한 primary키다
			var quantity = $(item).find('.quantity').html();
			//class이름이 quantity를 찾아서 html로 뽑아낸다
			//현재 이 item_id에 대한 주문수량
			return { item_id : item_id, quantity: quantity };
			//item_id(문자열) : item_id(변수 item_id)
			//자바스크립트는 딕셔너리의 경우에 따옴표를 안해도 문자열로 인식한다
		});

		var filtered = _.filter(mapped, function(item){
			return item.quantity > 0;
			//0보다 큰 item만 반환해준다
		});

		if ( filtered.length > 0){

			//실제 주문한 경우가 있는 상황
			var args = $.param(_.object(_.map(filtered, _.values)));
			//파이썬에 사전과같이 데이터를 넘기게되면
			//문자열을 만들어낸다
			var url = $(this).attr('href') + '?' + args;
			//이동할 주소를 가지고와서
			$(this).attr('href', url);
			//완성된 주소
			return true;
			//참이면 href이동
		}
		else {
			//모든 메뉴가 0인경우는?
			alert('상품 수량을 선택해주세요.');
		}

		return false;
		//거짓이면 alert 호출 후 이동하지않음
		});
});
</script>
{% endblock %}